services:
  app: 
    image: ubuntu:latest
    command: sh -c "sudo ./xdp_buzz_user"
    working_dir: /app

  nginx-backend-1:
    image: nginxdemos/hello:plain-text
    
  nginx-backend-2:
    image: nginxdemos/hello:plain-text
